
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.97/sell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.97
    port: 6379
server:
  context-path: /sell
  port: 8080

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #  path: F:\Projects\IDEAProjects\sell
#  file: F:\Projects\IDEAProjects\sell.log
#  level:
#    come.zwb.LoggerTest:debug

wechat:
  mpAppId: wx50cc4b29941960d6
  mpAppSecret: 234234

  openAppId: 2342432
  openAppSecret: 3242343

projectUrl:
  wechatMpAuthorize: 127.0.0.1:8080
  wechatOpenAuthorize: 127.0.0.1:8080
  sell: 127.0.0.1:8080
